### ISSUE TITLE
Generated connect.go package seems to have faulty imports

### ISSUE THREAD

**Issue by harshpreet93** [bufbuild/connect-go#287]
I'm pretty sure I'm doing something here, but I'm trying to swap out grpc-go with connect in a new service and the generated code seems to not be able to import the package that it's in.  The error screenshot is attached below:
![image](https://user-images.githubusercontent.com/3123326/172748235-2905a34c-adf5-41ea-a736-3ad982b3c29c.png)

The contents of the buf.gen.yaml are as follows:

```
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/harshpreet93/1000x/backend/internal/gen
plugins:
  - name: go
    out: gen
    opt: paths=source_relative
  - name: connect-go
    out: gen
    opt: paths=source_relative
```

The contents of the buf.work.yaml:

```
version: v1
directories:
  - proto
```

The contents of the service.proto file is:

```
syntax = "proto3";
package buf.connect.thousandx.v1;
option go_package = "thousandx.v1";


service ThousandXService {
    rpc Login(LoginRequest) returns (LoginResponse) {}
    rpc RegisterProvider(ProviderRegistrationRequest) returns (ProviderRegistrationResponse) {}
    rpc RequestTask(TaskRequest) returns (TaskResponse) {}
}

message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    string token = 1;
}

message ProviderRegistrationRequest {
    string username = 1;
    string password = 2;
    string name = 3;
    string email = 4;
    string phone = 5;
    string address = 6;
    string city = 7;
    string state = 8;
    string zip = 9;
    // string country = 10;
}

message ProviderRegistrationResponse {
    string token = 1;
}

message TaskRequest {
    string token = 1;
    string task_id = 2;
}

message TaskResponse {
    string task_id = 1;
    string task_name = 2;
}
```

Do you know what would cause this problem? Please let me know if you need any other information. 

PS: I love the idea of this project!
