### ISSUE TITLE
CORS options

### ISSUE THREAD

**Issue by bumberboy** [bufbuild/connect-go#499]
Hello there!

I'm trying to build a go backend and a nodejs react frontend with connect. I have generated the server stubs for go and I use connect-query to generate the client.

However I'm having difficulty following the tutorial to enable cors on the go backend. Is there an option for this? I've tried creating an interceptor but I'm still getting `CORS missing allow origin` error.

```
func CorsInterceptor() connect.UnaryInterceptorFunc {
	interceptor := func(next connect.UnaryFunc) connect.UnaryFunc {
		return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
			req.Header().Set("Access-Control-Allow-Origin", "*")
			req.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
			req.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
			return next(ctx, req)
		}
	}
	return interceptor
}
```

Here is my buf.gen.yaml:
```
version: v1
plugins:
  - plugin: go
    out: gen/
    opt: paths=source_relative
  - plugin: connect-go
    out: gen/
    opt: paths=source_relative
  - plugin: buf.build/bufbuild/connect-query
    out: ./../frontend/gen
    opt: target=ts
  - plugin: buf.build/bufbuild/es
    out: ./../frontend/gen
    opt: target=ts
    ```
